config/routes.rb
RobertScott::Application.routes.draw do
  resources  :messages

  root 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :email, :name, :body

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/video.rb
class Video < ActiveRecord::Base
  validates_uniqueness_of :video_id

  def self.create_from_youtube_videos
    YouTube.retrieve_videos.each do |video|
      begin
        create!(title: video.title, 
                description: video.description,
                video_id: video.resourceId['videoId'],
                position: video.position,
                thumb_url: video.thumbnails['medium']['url'],
                published_at: DateTime.parse(video.publishedAt))
      rescue
        next
      end
    end
  end

end

app/models/you_tube.rb
class YouTube
  class << self
    def playlist_id
      'UU34xp0_WvobosrCJeBTlmYg'
    end

    def api_key
      ENV['RS_YOUTUBE_KEY']
    end

    def playlist_url(page_token = nil)
      "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&"\
      "playlistId=#{playlist_id}&key=#{api_key}&maxResults=50&pageToken=#{page_token}"
    end

    def get_playlist(page_token = nil)
      HTTParty.get(playlist_url(page_token), verify: false)
    end

    def retrieve_videos
      page_token = ''
      videos     = []
      while page_token != nil do
        response = get_playlist(page_token)
        response['items'].map { |v| videos << OpenStruct.new(v['snippet']) }
        page_token = response['nextPageToken']
      end
      videos
    rescue => ex
      ap "Error retrieving videos: #{ex.message}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:type, :first_name, :last_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @videos = Video.all.order(published_at: :desc)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.create(message_params)
    if @message.save
      flash.now[:success] = 'Success! Your message has been sent.'
      redirect_to root_path
    else
      flash.now[:error] = 'Whoops! All fields are required.'
      render 'new'
    end
  end

  private

  def message_params
    params.require(:message).permit(:email, :name, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    (page_title.presence || 'Entertaining Short Videos') + ' | RobertScott'
  end

  def markdown(text)
    html = Redcarpet::Render::HTML.new(prettify: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(html, space_after_headers: true, fenced_code_blocks: true)
    markdown.render(text).html_safe
  end

  def generate_form_errors(errors)
    content_tag(:div, class: 'error') do
      'Oops. Something went wrong:'.html_safe +
      content_tag(:ul) do
        errors.full_messages.map { |message| content_tag(:li, message) }.join.html_safe
      end
    end
  end

  def video_url(video_id)
    "https://www.youtube.com/watch?v=#{video_id}"
  end

  def subscribe_url
    'https://www.youtube.com/channel/UC34xp0_WvobosrCJeBTlmYg?sub_confirmation=1'
  end

  def subscribe_button(text = 'Subscribe')
    link_to icon('youtube-play', "#{text}"), subscribe_url, 
    class: 'waves-effect waves-light btn red white-text', target: '_blank'
  end

  def icon(icon, text = nil, html_options = {})
    text, html_options = nil, text if text.is_a?(Hash)

    content_class = "fa fa-#{icon}"
    content_class << " #{html_options[:class]}" if html_options.key?(:class)
    html_options[:class] = content_class

    html = content_tag(:i, nil, html_options)
    html << ' ' << text.to_s unless text.blank?
    html
  end
end

app/views/home/index.html.erb
<div>
  <div class='cover-image'>
    <div class='center-align'>
      <div class='cover-primary'>
        <div id='cover-text-a'>Robert<b>Scott</b></div>
        <div id='cover-text-b'>Entertaining Short Videos</div>
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <div class='divider'></div>
  <h3 class='red-text text-lighten-1'>Season <b>1</b></h3>

  <%= react_component 'Videos', { data: @videos } %>

  <div class='divider'></div>
  <div class='row center-align' style='margin: 40px 0;'>
    Rate, Comment, and <span class='inline-subscribe-button'><%= subscribe_button %></span>
  </div>
  <div class='divider'></div>
</div>

<%= react_component 'Player' %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% unless value.blank? || value.length < 2 %>
    <div class='alert alert-<%= key %> alert-dismissible z-depth-1' role='alert'>
      <div><%= value %></div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68624659-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<div class='navbar-fixed'>
  <nav>
    <div class='nav-wrapper' style='margin: 0 10px;'>
      <%= link_to root_path, class: 'brand-logo' do %>
        <div class='center-align'>Robert<b>Scott</b></div>
      <% end %> 
      <a data-activates='mobile-sidebar' class='button-collapse'><i class='mdi-navigation-menu'></i></a>
      <ul id='nav-mobile' class='right hide-on-med-and-down'>
        <li><%= link_to icon('youtube'),     'http://bit.ly/1Ll2sd7',   target: '_blank' %></li>
        <li><%= link_to icon('google-plus'), 'http://bit.ly/1VIvk5Q',   target: '_blank' %></li>
        <li><%= link_to icon('facebook'),    'http://on.fb.me/1MhBteP', target: '_blank' %></li>
        <li><%= link_to icon('twitter'),     'http://bit.ly/1GzD3GW',   target: '_blank' %></li>
        <li><%= link_to 'Contact',           new_message_path %></li>
      </ul>
      <ul class='side-nav dark-side-nav' id='mobile-sidebar'>
        <li><%= link_to icon('times-circle', 'Close'),  'javascript:void(0)', class: 'close-mobie-sidebar' %></li>
        <li><%= link_to icon('home', 'Home'),           root_path %></li>
        <li><%= link_to icon('youtube', 'YouTube'),     'http://bit.ly/1Ll2sd7',   target: '_blank' %></li>
        <li><%= link_to icon('google-plus', 'Google+'), 'http://bit.ly/1VIvk5Q',   target: '_blank' %></li>
        <li><%= link_to icon('facebook', 'Facebook'),   'http://on.fb.me/1MhBteP', target: '_blank' %></li>
        <li><%= link_to icon('twitter', 'Twitter'),     'http://bit.ly/1GzD3GW',   target: '_blank' %></li>
        <li><%= link_to icon('envelope', 'Contact'),     new_message_path %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en' prefix='og: http://ogp.me/ns# website: http://ogp.me/ns/website#'>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'https://lh3.googleusercontent.com/-ApmkKRriEl8/AAAAAAAAAAI/AAAAAAAAAAA/YPy3ezELuqc/s92-c-k-no/photo.jpg' %>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'>
    <%= content_for :head %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <main>
      <%= yield %>
    </main>

    <%= render 'layouts/google_analytics' %>
  </body>
</html>

app/views/messages/new.html.erb
<%= provide(:title, 'Contact Us') %>
<div class='container'>
  <div class='row'>
    <div class='col l6 offset-l3 m8 offset-m2 s12'>
      <div class='row'>
        <div class='col s12'>
          <h4 class='center-align'>Contact Robert<b>Scott</b> </h4>
          <div class='card'>
            <div class='card-content'>
              <small class='block grey-text text-lighten-1 center-align'>All Fields Required</small>
              <%= form_for @message do |f| %>
                <div class='row'>
                  <div class='input-field col s12'>
                    <i class='mdi-action-account-circle active prefix'></i>
                    <%= f.text_field :name, autofocus: true %>
                    <%= f.label      :name, 'Your Name', class: 'active' %>
                  </div>
                </div>
                <div class='row'>
                  <div class='input-field col s12'>
                    <i class='mdi-communication-email prefix'></i>
                    <%= f.email_field :email %>
                    <%= f.label       :email %>
                  </div>
                </div>
                <div class='row'>
                  <div class='input-field col s12'>
                    <i class='mdi-editor-insert-comment prefix'></i>
                    <%= f.text_area :body, rows: 4, class: 'materialize-textarea' %>
                    <%= f.label     :body, 'Message' %>
                  </div>
                </div>
                <div class='row'>
                  <div class='col s12 right-align'>
                    <%= button_tag icon('send', 'Send'), type: 'submit', class: 'waves-effect waves-light btn red' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>